### ISSUE TITLE
Git Integration - Rebase Permission Denied

### ISSUE THREAD

**Issue by Coder206** [jankeromnes/janitor#25] opened 2016-08-17 01:54 UTC
When I trying to rebase code for Servo, I had trouble rebasing (and squashing) my changes.
The solution is inconvenient but is using `sudo`.

Solution:

To start `sudo git rebase -i HEAD~yourNumberHere`
** Rebase as usual here until about save **
To quit `:wq!`

**Comment by Coder206** [comment] 2016-08-17 01:54
It would be great to fix this though.

**Comment by jankeromnes** [comment] 2016-08-25 17:44
That's weird, and it does look like a bug that should be fixed for good. (Note: In general, issues with specific project images should live under the [dockerfiles](https://github.com/jankeromnes/dockerfiles) repository).

However, I was not able to reproduce that bug in a fresh Servo environment:

    user@machine:~/servo$ touch bla
    user@machine:~/servo$ git add bla
    user@machine:~/servo$ git config user.email "user@domain.com" && git config user.name "User"
    user@machine:~/servo$ git commit -m "added bla"
    [master 986ecc3] added bla
    user@machine:~/servo$ git fetch origin && git rebase origin/master
    First, rewinding head to replay your work on top of it...
    Applying: added bla

Is there something special about your environment? Maybe you used `git` with `sudo` before and accidentally changed ownership of some files in the `.git` directory?

**Comment by Coder206** [comment] 2016-08-25 18:07
@jankeromnes I may have done so with the `.git` directory. Would there be a way of changing it back?

**Comment by jankeromnes** [comment] 2016-08-25 18:55
You can force every file in the `.git` folder recursively to be owned by `user` instead of `root` by running:

    sudo chown user:user -R .git

I have bad memories with `.git` / `.svn` folders and `sudo` where I was forced to save my changes and destroy the repository entirely. Hopefully it will work out better for you!

**Comment by Coder206** [comment] 2016-08-25 18:59
@jankeromnes Thanks for this!

**Closed** 2016-08-25 20:35 UTC
